[build]
publish = "public"
command = "npm run build"
functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/public-data/award"
  to = "/public-data/awards"
  status = 301
  force = true
